name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout build
        uses: actions/checkout@v3
        with:
          path: build
      - name: Checkout release
        uses: actions/checkout@v3
        with:
          ref: release
          path: release
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
        working-directory: build
      - run: yarn build
        working-directory: build
      - name: Remove existing, then copy and commit build files to release branch
        working-directory: release
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git rm -rf .
          git clean -fxd
          cp -r $GITHUB_WORKSPACE/build/dist/index.js .
          cp $GITHUB_WORKSPACE/build/package.json .
          cp $GITHUB_WORKSPACE/build/README.md .
          git add --all
          git commit -m "Release commit from Github Actions"
          git push
