name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - name: Release to git release branch
        run: |
          COMMIT_EMAIL="$(git log --format='%ae' main | tail -n1)"
          COMMIT_USER_NAME="$(git log --format='%an' main | tail -n1)"
          git config --local user.email "$COMMIT_EMAIL"
          git config --local user.name "$COMMIT_USER_NAME via Github Action"
          git checkout --orphan release
          git reset
          git add -f package.json dist README.md
          git commit -m "Release commit from Github Actions"
          git push origin release:release --force
